swagger: "2.0"
info:
  description: "Get weather data of airports"
  version: "1.0.0"
  title: "MomenGo API"
  termsOfService: "http://localhost/terms/"
  contact:
    email: "apiteam@momengo.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
tags:
  - name: "Weather"
    description: "Everything about weather"
    externalDocs:
      description: "Find out more"
      url: "http://swagger.io"
  - name: "Airports"
    description: "Operations about airports"
    externalDocs:
      description: "Find out more about our airports"
      url: "http://swagger.io"
schemes:
  - "http"
paths:
  /search:
    get:
      tags:
        - "search"
      summary: "Returns a list of measure that match the search criteria."
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "search"
      produces:
        - "application/json"
      parameters:
        - name: "start_date"
          in: "query"
          description: "Start date"
          required: false
          type: "string"
        - name: "end_date"
          in: "query"
          description: "End date"
          required: false
          type: "string"
        - name: "iata"
          in: "query"
          description: "IATA code"
          required: false
          type: "string"
        - name: "type"
          in: "query"
          description: "Type of measurement"
          required: false
          type: "string"
          enum:
            - "temperature"
            - "pressure"
            - "wind"
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SearchResult"
        400:
          description: "Bad Request"
  /pet/{petId}:
    get:
      tags:
        - "pet"
      summary: "Find pet by ID"
      description: "Returns a single pet"
      operationId: "getPetById"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - name: "petId"
          in: "path"
          description: "ID of pet to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Airports"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
definitions:
  Airports:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
  SearchResult:
    type: "object"
    properties:
      type:
        type: "string"
        enum:
          - "temperature"
          - "pressure"
          - "wind"
      name:
        type: "string"
        example: "doggie"
      photoUrls:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
      status:
        type: "string"
        description: "pet status in the store"
        enum:
          - "available"
          - "pending"
          - "sold"
    xml:
      name: "Pet"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"