/*
 * MomenGo API
 *
 * Get weather data of airports
 *
 * API version: 1.0.0
 * Contact: apiteam@momengo.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
)

func GetCaptorById(w http.ResponseWriter, r *http.Request) {
	//TODO: Get captor using redigo
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
