/*
 * MomenGo API
 *
 * Get weather data of airports
 *
 * API version: 1.0.0
 * Contact: apiteam@momengo.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"myproject/cmd/redisMqtt"
	"myproject/internal/entities"
	"net/http"
	"strings"
	"time"
)

func Search(w http.ResponseWriter, r *http.Request) {
	fmt.Println("[" + time.Now().String() + "] : Incoming request on ' " + r.URL.Path + "?" + r.URL.RawQuery + "'")

	data := r.URL.Query()

	startDate := strings.Split(data.Get("start_date"), "-")
	if len(startDate) != 3 {
		badRequest(w)
		return
	}
	endDate := strings.Split(data.Get("end_date"), "-")
	if len(endDate) != 3 {
		badRequest(w)
		return
	}
	iata := data.Get("iata")
	if iata == "" {
		iata = "*"
	}
	measureType := data.Get("type")
	query := data.Get("query")
	if measureType == "" {
		measureType = "*"
	}
	moyenne := false
	if data.Get("moyenne") == "" || data.Get("moyenne") == "true" {
		moyenne = true
	}

	//TODO: Write the redis query

	rc := redisMqtt.CreateARedisClientFromConfig(entities.GetConfig())
	res, err := rc.Find(query)
	if err != nil {
		badRequest(w)
		return
	}

	fmt.Println(res)

	if moyenne {

	}

	jsonRes := "["

	for _, v := range res {
		jsonRes += "{ \"type\" : \"" + v.Measure + "\"},"
	}

	jsonRes += "]"

	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write([]byte(jsonRes))

}

func badRequest(w http.ResponseWriter) {
	w.WriteHeader(400)
	_, _ = w.Write([]byte("Bad request"))
}
