/*
 * MomenGo API
 *
 * Get weather data of airports
 *
 * API version: 1.0.0
 * Contact: apiteam@momengo.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Measure struct {
	Timestamp string `json:"timestamp,omitempty"`

	Value float32 `json:"value,omitempty"`
}
